name : CI2

on :
  push :
    branches : [master]
  pull_request :
    branches : [master]

jobs :
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version : [14.x]
    
    steps:
    - uses : actions/checkout@v2
    - name : Use Node.js ${{matrix.node-version}}
      uses : actions/setup-node@v1
      with:
        node-version : ${{matrix.node-version}}
    - name : Install dependencies
      run: |
        npm ci
    - name : Build the app 
      run: |
        npm run build
    - name : Run Components Test
      run: |
        npm run test
    - name : Start the app
      run: |
        npm start & 
        npx wait-on --timeout 60000
